<?php

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_System_Storm_Event_Model_Test extends TestCase
{
  protected $cradle;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->cradle = cradle();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   */
  public function testModelCreate()
  {
    $payload = $this->makePayload();

    $payload['request']->setStage([
      'schema' => 'foo',
      'foo_title' => ['value' => 'Foo Bar 3', 'bind' => true],
      'foo_detail' => 'This is foo bar 3',
      'foo_amount' => ['value' => 12, 'bind' => false],
      'dont_error' => 'ok'
    ]);

    $actual = $this->cradle->method(
      'system-model-create',
      $payload['request'],
      $payload['response']
    );

    $this->assertTrue(!$payload['response']->isError());

    $this->assertEquals(1, $actual);
  }

  protected function makePayload()
  {
    $payload = $this->cradle->makePayload();
    $payload['request']->meta('mysql', include(__DIR__.'/assets/mysql.php'));
    return $payload;
  }
}
