<?php

namespace Cradle\Package\Storm;

use PHPUnit\Framework\TestCase;

use StdClass;

use Cradle\Storm\Engine\MySql;
use Cradle\Framework\FrameworkHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Cradle_Framework_Storm_StormPackage_Test extends TestCase
{
  /**
   * @var FrameworkHandler
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    //this is the OOP version of cradle
    $this->object = new FrameworkHandler;
    $testRoot = __DIR__;
    $packageRoot = dirname($testRoot);

    //now register storm
    $this->object->register('cradlephp/cradle-storm', $packageRoot);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers Cradle\Package\Storm\StormPackage::loadPDO
   */
  public function testLoad()
  {
    $actual = $this->object->package('storm')->getPackageMap();
    $this->assertInstanceOf(StormPackage::class, $actual);

    $this->object->package('storm')->loadConfig([
      'type' => 'mysql',
      'host' => '127.0.0.1',
      'port' => '3306',
      'name' => 'testing_db',
      'user' => 'root',
      'pass' => ''
    ]);

    $actual = $this->object->package('storm')->getPackageMap();
    $this->assertInstanceOf(MySql::class, $actual);
  }
}
